timezone: Asia/Tokyo

# GoatCounter site code (subdomain): https://<code>.goatcounter.com
goatcounter: hinayuki64

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
